; include accumulate.scm

(define (accumulate-n op init seqs)
  (define (head sequences)
    (if (or (null? sequences) (null? (car sequences)))
        (list)
        (cons (car (car sequences))
              (head (cdr sequences)))))
  (define (rest sequences)
    (if (or (null? sequences) (null? (car sequences)))
        (list)
        (cons (cdr (car sequences))
              (rest (cdr sequences)))))
 (if (null? (car seqs))
   (list)
   (cons (accumulate op init (head seqs))
         (accumulate-n op init (rest seqs)))))
